version: 2.1
executors:
  node-lts:
    docker:
      - image: cimg/node:lts
jobs:
  build:
    executor: node-lts
    steps:
      - checkout
      - run:
          name: "Run Tests"
          command: |
            cd InvApp
            npm install
            npm run testFinal
